name: Deploy to Heroku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Git configuration
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Set up Heroku Repo
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

    - name: Unshallow the repository
      run: git fetch --all --unshallow

    - name: Push to Heroku
      run: git push heroku main --force
